# To enable worker nodes to join your cluster:
#
#   $ aws eks --region us-west-2 update-kubeconfig --name cloud-devops-capstone-project-EksCluster
#   $ kubectl apply -f aws-auth-cm.yml
#
# See: https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  # <ARN of instance role (not instance profile)>
  mapRoles: |
    - rolearn: arn:aws:iam::853001741663:role/eks-node-group-stack-NodeInstanceRole-911S38ZCOLVU
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
