---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Thomas Weibel - Udacity Cloud DevOps Engineer Nanodegree

  Amazon EKS Cluster

  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html

# Parameters
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

# Resources
Resources:
  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.14"
      RoleArn: !GetAtt EksClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}-SecurityGroup
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue:
                Fn::Sub: ${EnvironmentName}-SubnetIds

# Outputs
Outputs:
  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt EksClusterRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-RoleArn

  EksClusterId:
    Description: EKS cluster ID
    Value: !Ref EKSCluster
    Export:
      Name: !Sub ${EnvironmentName}-EksClusterId
