---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Thomas Weibel - Udacity Cloud DevOps Engineer Nanodegree

  Amazon EKS Cluster

  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html

# Parameters
Parameters:
  StackName:
    Type: String
    Description: Stack name that will be prefixed to resource names

# Resources
Resources:
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: !Sub "${StackName}-EksServiceRole"

  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${StackName}-EksCluster"
      Version: "1.14"
      RoleArn: !GetAtt EksServiceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${StackName}-SecurityGroup
        SubnetIds:
            Fn::Split:
                - ","
                - Fn::ImportValue:
                      Fn::Sub: ${StackName}-SubnetIds

# Outputs
Outputs:
  RoleArn:
    Description: The role that Amazon EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt EksServiceRole.Arn
    Export:
      Name: !Sub ${StackName}-EksRoleArn
      
  EksCluster:
    Description: EKS cluster name
    Value: !Ref EksCluster
    Export: 
        Name: !Sub ${StackName}-EksCluster
