apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-developer-nanodegree
  labels:
    app: cloud-developer-nanodegree
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-developer-nanodegree
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-developer-nanodegree
    spec:
      containers:
      - image: ikhono/cloud-developer-nanodegree:tested
        imagePullPolicy: Always
        name: cloud-developer-nanodegree
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-developer-nanodegree
spec:
  type: LoadBalancer
  selector:
    app: cloud-developer-nanodegree
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80